[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = "4.5.39"
fern = { version = "0.7.1", features = ["colored"] }
log = "0.4.27"
thiserror = "2.0.12"
backtrace = "0.3.75"
colored = "3.0.0"
sysinfo = "0.35.2"
terminal_size = "0.4.2"