[package]
name = "marston"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true, features = ["derive"] }
toml = { workspace = true }
fs-err = { workspace = true }

[lints]
workspace = true
